ARG INPUT_DOCKER_REGISTRY=andahme



FROM ${INPUT_DOCKER_REGISTRY}/debian:base AS build-essential


RUN apt-get update && \
    apt-get install --yes --no-install-recommends build-essential

RUN useradd --comment "Build User" --create-home --uid 1011 builder

RUN mkdir /workspace && \
    chmod 777 /workspace


WORKDIR /workspace

