ARG INPUT_DEBIAN_ARCH=amd64

ARG INPUT_DOCKER_REGISTRY=andahme

ARG INPUT_JAVA_MAJOR=11



FROM ${INPUT_DOCKER_REGISTRY}/debian:base AS base

ARG INPUT_DEBIAN_ARCH

ARG INPUT_JAVA_MAJOR


ENV JAVA_HOME /usr/lib/jvm/java-${INPUT_JAVA_MAJOR}-openjdk-${INPUT_DEBIAN_ARCH}


RUN apt-get update && \
    apt-get install --yes --no-install-recommends openjdk-${INPUT_JAVA_MAJOR}-jre-headless

