FROM andahme/build-essential:testing


RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install --yes --no-install-recommends python3 python3-dev python3-pip python3-setuptools python3-venv python3-wheel

