FROM andahme/build-essential


RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install --yes --no-install-recommends python python-dev python-pip python-setuptools python-wheel


